services:
  identity_db:
    container_name: identity_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"

  account_db:
    container_name: account_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: account_db
    ports:
      - "5431:5432"

  expense_db:
    container_name: expense_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: expense_db
    ports:
      - "5434:5432"

  income_db:
    container_name: income_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: income_db
    ports:
      - "5435:5432"

  report_db:
    container_name: report_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: report_db
    ports:
      - "5436:5432"

  discoveryservice:
    image: dockerfile-discoveryservice:0.0.1
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: discoveryservice
      SERVER_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: discoveryservice
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"

  api-gateway:
    image: dockerfile-apigateway:0.0.1
    ports:
      - "8082:8082"
    depends_on:
      - discoveryservice
      - identity-service

  identity-service:
    image: dockerfile-identity:0.0.1
    ports:
      - "8088:8088"
    depends_on:
      - identity_db
      - discoveryservice

  account-service:
    image: dockerfile-account:0.0.1
    ports:
      - "8099:8099"
    depends_on:
      - account_db
      - discoveryservice

  income-service:
    image: dockerfile-incomeservice:0.0.1
    ports:
      - "8070:8070"
    depends_on:
      - income_db
      - identity_db
      - account_db
      - discoveryservice

  expense-service:
      image: dockerfile-expenseservice:0.0.1
      ports:
        - "8071:8071"
      depends_on:
        - expense_db
        - account_db
        - discoveryservice

  report-service:
      image: dockerfile-reportservice:0.0.1
      ports:
        - "8073:8073"
      depends_on:
        - report_db
        - discoveryservice

  recommendation-service:
      image: dockerfile-recommendationservice:0.0.1
      ports:
        - "8077:8077"
      depends_on:
        - discoveryservice

  admin-service:
      image: dockerfile-adminservice:0.0.1
      ports:
        - "8100:8100"
      depends_on:
        - discoveryservice

  analysis-service:
      image: dockerfile-analysisservice:0.0.1
      ports:
        - "8091:8091"
      depends_on:
        - discoveryservice
