spring:
  application:
    name: expense-service
  profiles:
    active: database
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_db
    username: my_user
    password: 12345
  jpa:
    properties:
      hibernate:
        default_schema: public
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  liquibase:
    change-log: db.changelog_4/main-changelog_4.xml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8071

eureka:
  client:
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
